<?php
declare(strict_types=1);

use FriendsOfHyva\EmailSuggestions\Magewire\EmailSuggestions;
/** @var EmailSuggestions $magewire */
?>
<div xmlns="http://www.w3.org/1999/html">
    <input type="text" wire:model.defer="fullname" placeholder="Your name" /><br />
    <input type="email" wire:model.defer="email" placeholder="Your email" /><br />
    <textarea wire:model.defer="message" placeholder="Your message..."></textarea>
    <button type="button" wire:click="sendMessage">
        <?= __('Send Message') ?>
    </button>
</div>
