<?php
declare(strict_types=1);

use FriendsOfHyva\EmailSuggestions\Magewire\EmailSuggestions;
/** @var EmailSuggestions $magewire */
?>
<div x-data="emailHelper">
    <input type="text" x-model.defer="fullname" placeholder="Your name" /><br />
    <input type="email" :value="customEmail" @change="checkEmail" @blur="checkEmail" placeholder="Your email" /><br />
    <div @click="correctEmail" id="emailSuggestion"></div><br />
    <textarea x-model.defer="message" placeholder="Your message..."></textarea>
    <button type="button" @click="sendMessage">
        <?= __('Send Message') ?>
    </button>
    <script>
        function emailHelper() {
            return {
                fullname: '',
                customEmail: '',
                message: '',
                finalEmailSuggestion: '',
                emailSuggestion: document.getElementById("emailSuggestion"),
                customDomains: JSON.parse('<?= $magewire->domains ?>'),
                checkEmail(event) {
                    const emailValue = event.target.value;
                    const suggestion = EmailSpellChecker.run({
                        email: emailValue,
                        domains: [...EmailSpellChecker.POPULAR_DOMAINS, ...this.customDomains]
                    });
                    if (suggestion) {
                        emailSuggestion.innerHTML = "Did you mean <span style=\"border-bottom: 1px solid;\">" + suggestion.full + "</span>?";
                        this.finalEmailSuggestion = suggestion.full;
                    }
                },
                correctEmail() {
                    this.customEmail = this.finalEmailSuggestion;
                    this.emailSuggestion.innerHTML = "";
                }
            }
        }
    </script>
</div>
